language: python
python:
  - 3.7
  - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

cache:
  apt: false
  directories:
    - $HOME/.cache/pip
    - $HOME/lib


sudo: required
dist: xenial

install:
  - pip install -r ci_requirements.txt
  - pip install .

script:
  - cd $TRAVIS_BUILD_DIR/tests
  - coverage run Tests.py

after_success:
  - cd $TRAVIS_BUILD_DIR/tests
  - codecov
