channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - alabaster
  - beautifulsoup4
  - bleach
  - blosc
  - bokeh
  - codecov
  - coverage
  - ete3
  - h5py
  - hdf5
  - html5lib
  - ipdb
  - ipykernel
  - ipyparallel
  - ipysheet
  - ipython
  - ipython_genutils
  - ipywidgets
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - nbconvert
  - nbformat
  - nbsphinx
  - ncurses
  - notebook
  - numexpr
  - numpy
  - pandas
  - pandoc
  - pandocfilters
  - pip
  - pivottablejs
  - pytables
  - python
  - qgrid
  - requests
  - scipy
  - selenium
  - setuptools
  - setuptools_scm
  - soupsieve
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - sqlite
  - biopython
  - matplotlib
  - pip
  - voila
  - pip:
    - arxivcheck
    - bibcure
    - bibtexparser
    - bqplot
    - coreapi
    - coreschema
    - cycler
    - docopt
    - doi2bib
    - feedparser
    - future
    - ipyaggrid
    - itypes
    - nbinteract
    - pillow
    - pubmed-lookup
    - pyham
    - simplejson
    - title2bib
    - toolz
    - traittypes
    - unidecode
    - uritemplate
